### ISSUE TITLE
Error with hyphen

### ISSUE THREAD

**Issue by tom-dr** [wearefractal/gulp-beautify#28]
With code
```css
@supports not (inset: 10px) {
  .articles-wrapper.grid {
    margin: 0 0 5rem 0;
  }

  @media screen and (min-width: 750px) {
    .articles-wrapper.grid {
      margin-bottom: 7rem;
    }
  }
}
```
Be beautifyed like this
```css
@supports not(inset: 10 px) {
  .articles - wrapper.grid {
    margin: 0 0 5 rem 0;
  }
  @media screen and(min - width: 750 px) {
    .articles - wrapper.grid {
      margin - bottom: 7 rem;
    }
  }
}
```
